names = [
'Alexandre Silva',
'Christian Farina',
'Leandro Filho',
'Geraldo',
'Luiz Uchoa',
'Leandra Palma',
'Thiago Rodrigues',
'Renato do Nascimento',
'Fernando Henrique',
'Vinicius Tardelli',
'Saulo Senna',
'Gilson Paulino',
'Nettuno',
'Theo Borges',
'Tiquinho',
'Wilian Malaquias',
'Iago Maia',
'Rodrigo Giannoni',
# 'Alyson David',
'Rayson Bernardo',
'Dirso Ament',
'Wanderson Silva',
# 'Maicon Texeira',
# 'Pedro Bastos',
'Yuichi Kobayashi',
'Geraldo Pereira',
'Daniel Bragança',
'Eduardo Rubik',
'Aurelio Felicio',
'Ronie Araujo',
'Rafael Cavalcante',
'Anderson Salvi',
'Willyan Ribeiro',
'Mozer Barreto',
'João Marcelo Farina',
'Rapha Ferreira',
'Aurelio Felicio',
'Marcelo Cruz',
'Thalia Alves',
'Giovane Larangeira',
'Marcão',
# 'Jose Alberto',
'Andre Muzzo',
'Nicson Silva',
'Ivson Alves',
# 'Rafael Ferreyro',
'Rodrigo Bonotto',
'Aurelio Felicio',
'Tiago Passos',
# 'Cleilson Bezerra',
'Yuri Moura',
'Robson Moraes',
'Paulo Roque',
'Michell Silva',
# 'Dario Medeiros',
# 'Deivid Santana',
'Felipe Silva',
'Ivan Bianzeno',
'Marcello Murakami',
'Francisco Teixeira',
'Hiam Costa',
'Alexandre Nemetz',
'Bruno Quatrochi',
# 'Gercina Veloso',
'Rafael Trevizani',
'Leonardo Dambrós',
# 'Juliane Borges',
'Carlos Santos',
'Wesley Penido',
# 'Maicon Texeira',
'Leonardo Leite',
# 'Rafael Lopez',
# 'Mendonça Bezerra',
# 'Fabio Costa',
'Mateus Hessel',
'Edmundo Luna',
'Renato Vieira',
'Cleyton Ruiz',
# 'Lucio Silva',
'Jaime Costa',
# 'Lucas Araujo',
'Igor Heraclio',
'Wellington Muniz',
# 'George Rocha',
# 'Vitor Lourenco',
# 'Sebastião RJ',
# 'Fausto Gorodoski',
# 'Lucas Sterssio',
'Odirlei Klein',
# 'Alessandro Aparecido',
'Sergio Vitor',
# 'Hugo Junio',
'Aulisson Bianchet',
'Daniel Martins',
'Ivan Loiola',
# 'João Leite',
# 'Bruno Ruocco',
# 'Alan Silva',
# 'Adjael Porela',
'Paulo Barros',
'Cleilson Bezerra',
'Breno Santos',
# 'Carlos Henrique',
# 'Douglas Minuzzi',
# 'Nathan Caixeta',
# 'John Lennon',
# 'Rodrigo Lemos',
# 'Valmir Rodrigues',
'Dario Medeiros',
'Cleilson',
# 'Bernardo Camarotti',
# 'Eduardo Alves',
# 'Marcos Eduardo',
'Eduardo Oliveira',
# 'João Leite',
# 'Diogo Serafim',
'Diogo Mota',
'Fábio Biribilli',
'Everton Gonçalves',
# 'Alex Dumas',
# 'Daniel Portela',
'Gustavo Negreiros',
'Herbert Chagas',
# 'Jefferson Galdino',
'Allan Johannes',
'Telmo Santos',
# 'Kaue Lotice',
'Gabriel Assis',
'Diego Brunelli',
'Eduardo Rubik',
'Alex Lima',
# 'Lucas Serpa',
# 'Rodrigo de Mello',
'Tobias Alvarenga',
# 'Alessandro Rodrigues',
# 'Luiz Paulo',
# 'Manoel Souza',
# 'Leonardo Petró',
'Caio Antunes',
'Wasley Both',
# 'Bruno Estevam',
# 'Oswaldo Glaeser',
'Ricardo Giesel',
'Rodrigo Madeira',
'Alex Candido',
# 'Antônio Marcos',
# 'Oswaldo Glaeser',
'Luciano Sobrosa',
# 'José Sousa',
# 'Adriano Bobby',
# 'Diego Mendes',
# 'Cassiano Buffon',
# 'Leonardo Guedes',
# 'Vinicius Soares',
'Marcos Paulo',
# 'Lucas Moretto',
'Estevão Cardoso',
'Rafael Enriquez',
# 'Matheus Ferreira',
'Oda Gerlach',
# 'José Carlos',
'Victor Rocha',
'Thiago Cozendey',
# 'Marcelo Augusto',
# 'CesarMarra',
# 'Rui Marques',
'Leonardo Ribeiro',
# 'Paulo Froese',
# 'Thiago Lanza',
'Marcos Vinicius',
'Jacques Caldas',
'Alexandre Kibritte',
# 'Felipe Ribeiro',
'Rodrigo Chaves',
# 'Atonielson Rocha',
# 'Mauricio Vilarino',
# 'Dagoberto Gonçalves',
# 'Rodrigo Rodrigues',
# 'Henrique Freitas',
# 'Igor Labiak Junior',
# 'Pedro Takao',
'Diego Santos',
# 'Jhonatan Vargas',
# 'Miquéias Silva',
'Bruno Araujo',
# 'Rodrigo Souza',
'Andre Gonçalves',
'Luis Fonseca',
'Anderson Salvi',
'Leidson Souza',
'Lucas Santos',
'Rapha Mineto',
'Abel Thiago',
'Rafael Ferreyro',
'Marcelo Moreira',
# 'Promo GetUp',
'Mendonça Bezerra',
'Rodrigo Milani Traldi',
'Rodrigo Fagundes',
'Samuel Terra',
'Vitor Campos',
'Jonathan Batista',
'Lucas Well',
'Matheus Canesk',
'Hugo Kitamura',
# 'Alexandre Ribeiro',
'Danilo Thyago',
'Anderson Silva',
'Itallo Gabriel',
'Sergio Nogueira',
'Rafael Barros',
'Maycon Caetano',
'Matheus de Oliveira',
'Per Johansson',
'Andre Gonçalves',
'Bruno Guimarães',
'Lucas Nogueira',
'Jonas Marcel',
'Nickael Ribeiro',
'Guilherme Gerber',
'Alison Negrinho',
'Vinícius Augusto',
'Roberto Alvisi'
]























usernames = [
'alexandre',
'christian',
'leandro',
'geraldo',
'luiz',
'leandra',
'thiago_rodrigues',
'renato_do_nascimento',
'fernando_henrique',
'vinicius_tardelli',
'saulo_senna',
'gilson_paulino',
'nettuno',
'theo_borges',
'tiquinho',
'wilian_malaquias',
'iago_maia',
'rodrigo_giannoni',
# 'alyson_david',
'rayson_bernardo',
'dirso_ament',
'wanderson_silva',
# 'maicon_texeira',
# 'pedro_bastos',
'@Yuichi1998',
'@geraldojhpereira',
'@DanielBraganca',
'eduardo_rubik',
'aurelio_felicio',
'ronie_araujo',
'rafael_cavalcante',
'anderson_salvi',
'willyan_ribeiro',
'mozer_barreto',
'jmfarina',
'rapha_ferreira',
'aurelio_felicio',
'marcelo_cruz',
'thalia_alves',
'giovane_larangeira',
'marcao',
# 'jose_alberto',
'AndreMuzzo',
'NicsonSilva',
'IvsonAlves',
# 'RafaelFerreyro',
'RodrigoBonotto',
'AurelioFelicio',
'TiagoPassos',
# 'CleilsonBezerra',
'YuriMoura',
'RobsonMoraes',
'PauloRoque',
'MichellSilva',
# 'DarioMedeiros',
# 'DeividSantana',
'FelipeSilva',
'IvanBianzeno',
'MarcelloMurakami',
'FranciscoTeixeira',
'HiamCosta',
'AlexandreNemetz',
'BrunoQuatrochi',
# 'GercinaVeloso',
'RafaelTrevizani',
'LeonardoDambros',
# 'JulianeBorges',
'CarlosSantos',
'WesleyPenido',
# 'MaiconTexeira',
'LeonardoLeite',
# 'RafaelLopez',
# 'MendonçaBezerra',
# 'FabioCosta',
'MateusHessel',
'EdmundoLuna',
'RenatoVieira',
'CleytonRuiz',
# 'LucioSilva',
'JaimeCosta',
# 'LucasAraujo',
'IgorHeraclio',
'WellingtonMuniz',
# 'GeorgeRocha',
# 'VitorLourenco',
# 'SebastiaoRJ',
# 'FaustoGorodoski',
# 'LucasSterssio',
'OdirleiKlein',
# 'AlessandroAparecido',
'SergioVitor',
# 'HugoJunio',
'AulissonBianchet',
'DanielMartins',
'IvanLoiola',
# 'JoaoLeite',
# 'BrunoRuocco',
# 'AlanSilva',
# 'AdjaelPorela',
'PauloBarros',
'CleilsonBezerra',
'BrenoSantos',
# 'CarlosHenrique',
# 'DouglasMinuzzi',
# 'NathanCaixeta',
# 'JohnLennon',
# 'RodrigoLemos',
# 'ValmirRodrigues',
'DarioMedeiros',
'Cleilson',
# 'BernardoCamarotti',
# 'EduardoAlves',
# 'MarcosEduardo',
'EduardoOliveira',
# 'JLeite',
# 'DiogoSerafim',
'DiogoMota',
'FabioBiribilli',
'EvertonGonçalves',
# 'AlexDumas',
# 'DanielPortela',
'GustavoNegreiros',
'HerbertChagas',
# 'JeffersonGaldino',
'AllanJohannes',
'TelmoSantos',
# 'KaueLotice',
'GabrielAssis',
'DiegoBrunelli',
'EduardoRubik',
'AlexLima',
# 'LucasSerpa',
# 'RodrigoMello',
'TobiasAlvarenga',
# 'AlessandroRodrigues',
# 'LuizPaulo',
# 'ManoelSouza',
# 'LeonardoPetro',
'CaioAntunes',
'WasleyBoth',
# 'BrunoEstevam',
# 'OswaldoGlaeser',
'RicardoGiesel',
'RodrigoMadeira',
'AlexCandido',
# 'AntonioMarcos',
# 'OswaldoGlaeser',
'LucianoSobrosa',
# 'JoseSousa',
# 'AdrianoBobby',
# 'DiegoMendes',
# 'Cassiano Buffon',
# 'LeonardoGuedes',
# 'vinibretz',
'MarcosPaulo',
# 'LucasMoretto',
'EstevaoCardoso',
'RafaelEnriquez',
# 'MatheusFerreira',
'OdaGerlach',
# 'JoseCarlos',
'VictorRocha',
'ThiagoCozendey',
# 'MarceloAugusto',
# 'CesarMarra',
# 'RuiMarques',
'LeonardoRibeiro',
# 'PauloFroese',
# 'ThiagoLanza',
'MarcosVinicius',
'JacquesCaldas',
'AlexandreKibritte',
# 'FelipeRibeiro',
'RodrigoChaves',
# 'AtonielsonRocha',
# 'MauricioVilarino',
# 'DagobertoGoncalves',
# 'RodrigoRodrigues',
# 'HenriqueFreitas',
# 'LabiakJunior',
# 'PedroTakao',
'DiegoSantos',
# 'JhonatanVargas',
# 'MiqueiasSilva',
'BrunoAraujo',
# 'RodrigoSouza',
'AndreGoncalves',
'LuisFonseca',
'AndersonSalvi',
'LeidsonSouza',
'LucasSantos',
'RaphaMineto',
'AbelThiago',
'RafaelFerreyro',
'MarceloMoreira',
# 'festevam999',
'MendonçaBezerra',
'RodrigoMilani',
'RodrigoFagundes',
'SamuelTerra',
'VitorCampos',
'JonathanBatista',
'LucasWell',
'MatheusCanesk',
'HugoKitamura',
# 'AlexandreRibeiro',
'DaniloThyago',
'AndersonSilva',
'ItalloGabriel',
'SergioNogueira',
'RafaelBarros',
'MayconCaetano',
'MatheusOliveira',
'PerJohansson',
'AndreGonçalves',
'BrunoGuimaraes',
'LucasNogueira',
'JonasMarcel',
'NickaelRibeiro',
'GuilhermeGerber',
'AlisonNegrinho',
'ViniciusAugusto',
'RobertoAlvisi'
]
























passwords = [
'sporting',
'gremio',
'leandro',
'palmeiras',
'sport',
'casalbettrader',
'rp_thiago@yahoo.com.br',
'renatonascimentoalmeida@hotmail.com',
'Mary@1908',
'tardellits@gmail.com',
'contato@fiodor.com.br',
'gilsongrajauink@gmail.com',
'nettuno82',
'cariocatheo',
'tiquinhoqa',
'malakagastao@gmail.com',
'iago.alves.maia@hotmail.com',
'giannoni@gmail.com',
# 'alysondavidbatera@gmail.com',
'rayson.bs@hotmail.com',
'adilsonantonioament@gmail.com',
'ws709959@gmail.com',
# 'maicontexeiradesouza@gmail.com',
# 'pedrohenriquesoaresbastos1@gmail.com',
'Yuichi1998@hotmail.com',
'geraldojhp@yahoo.com.br',
'danbraganca@gmail.com',
'eduardorubik@hotmail.com',
'aureliomatosfel@gmail.com',
'cs_de_valor',
'klcrcb@gmail.com',
'andersonsalvi@gmail.com',
'willyanribeiro021@gmail.com',
'mowcb1914@gmail.com',
'@jmfarina',
'@raphaelph52',
'aureliomatosfel@gmail.com',
'marcelocruz190381@gmail.com',
'thalia.alvesjs@gmail.com',
'giovanelarangeira22@gmail.com',
'oliveira.marcoantonio9@gmail.com',
# 'zezotte@yahoo.fr',
'@Andremuzzo',
'@nicsonsilva',
'@Valdomiro',
# '@rafaelferreyro',
'@Rodrigobonotoo',
'@aureliomatosfel',
'@Tiago520',
# '@Clei_Bezerra',
'@yuri_jose',
'@RobsonMoraes1',
'@pauloroque2',
'@michellsts',
# '@Dariomedguerra',
# '@Deividsantana',
'@prof.felipe1990',
'@ivanbianzeno',
'@marcello.yuji',
'@franciscoandreteixeira5',
'@hiamcosta224',
'@alexandrenemetz',
'@b.quatrochi',
# '@gsbveloso_silvania',
'@trevizanirafael',
'@nardo_quadros',
# '@julianepborges',
'@carlosdossoofi',
'@wesleynido',
# '@maicontexeiradesouza',
'@leonardoleite.cid',
# '@rafadaica3',
# '@mendoncabezerra',
# '@fabiokosta1',
'@mateushessel',
'@edmundodelunaneto',
'@renatotagarro',
'@ruiz.fabiano',
# '@isaeduda70',
'@jaimedasilvacosta',
# '@lucaspsicologo040810',
'@igor_heraclio',
'@muniz_cfo',
# '@georgerocha777',
# '@vmnsantos',
# '@gasista10',
# '@traderusany',
# '@LucasSter',
'@odirleiklein',
# '@aleapsantos',
'@sergiovitoor',
# '@hugojuniocruvinel007',
'@aulixxm',
'@shamandnl',
'@ilcfilho',
# '@Neto_leite',
# '@bruno.ruocco',
# '@alancarneirodasilva',
# '@adjael',
'@PauloAndreBarros',
'@Clei_Bezerra',
'@brenosantos250',
# '@henriquerobmar2017',
# '@Douglas_minuzzi',
# '@nathancaixeta7',
# '@LennonAlves',
# '@rodrigozx10',
# '@valmirramones10',
'@dario.natal',
'@clei.jr',
# '@becamarotti',
# '@eduardo-eduas',
# '@mec.eduardo',
'@duduoliveiradasilva10',
# '@jnetoleite93',
# '@diogoser',
'@diogofilipemota',
'@fabio_novavid',
'@evertongoncalves90',
# '@alex.dumas.15',
# '@DanielPortelaBR',
'@GugaNegreiros',
'@Herbertchagas',
# '@Galo_doido27',
'@allanjhff',
'@Telmo_CC',
# '@Kaue',
'@assiszz',
'@diego.brunelli',
'@eduardorubik',
'@alexmoreiralima',
# '@Lucas_Serpa',
# '@rodrigodemello1984',
'@tobiascalvarenga',
# '@alessandro.b.2',
# '@luizpaulo.braz',
# '@serralheriaatuall',
# '@lpo2707',
'@caioad',
'@wasleyboth',
# '@bestevam11',
# '@glaeser.neto',
'@ricardogiesel',
'@rodrigomadeiracosta',
'@alexcandidotjf',
# '@Tutuhidro',
# '@oswaldoglaeser',
'@sobrosasl91',
# '@josesousa85',
# '@Boby406',
# '@DiegoMendys',
# '@cassiano.buffon',
# '@leodalegendarios',
# '@vinibretz_cda',
'@marcoscorrectscore',
# '@LucasPim19',
'@estevao_cardoso',
'@rafaelenriquez',
# '@matheuszuruc',
'@gerlach.oda',
# '@josecarloslima962',
'@victorroc1',
'@thiagodurcocozendey',
# '@marceloaugustodias',
# '@cesarmarra',
# '@KET3L',
'@leonardoejanna',
# '@froesepaulo',
# '@thiagolanza19',
'@marcosviniciustp',
'@jacquescaldas',
'@alexandre',
# '@felipe2013.ribeiro',
'@lopeschv',
# '@Toni',
# '@mauriciolv2',
# '@dagvieira77',
# '@rodriguesRd',
# '@lhs.freitas',
# '@jrlabiak',
# '@pedrotakao58',
'@diegosantos199520',
# '@jhonatanvargas209.jv',
# '@Miqueias1990',
'@baraujo29',
# '@rodrigopedagogo2016',
'@brazil.miller',
'@lfonseca78',
'@Anderson_291',
'@Leidson1208',
'@lucaslinares84',
'@raphaelmineto',
'@abelthiago',
'@rafaelferreyro',
'@marcelomoreiraa70',
# '@festevam999',
'@Mendonca0810',
'@RMT',
'@fagundes1',
'@samucabxa1',
'@Camposap00',
'@jonathanmusic1',
'@wellucas',
'@Zoro',
'@hugouske',
# '@alexandredsribeiro7',
'@Thyagod',
'@agroanderss',
'@gabriel.wxz',
'@bbb.serginho',
'@Rafaelbarros1',
'@zMK47',
'@mmatheusoli18',
'@permj',
'@brazil.miller',
'@brunoguimaraes465',
'@lucasnfav',
'@jonas.mggeremias', # Uma semana a mais
'@nribeiro77',
'@guitgerber',
'@alison1905',
'@Viarc33',
'@roberto'
]
