# usuarios.py

# Lista de usuários permitidos
usuarios_permitidos = [
{'nome': 'Alexandre Silva', 'login': 'alexandre', 'senha': 'sporting'},
{'nome': 'Christian Farina', 'login': 'christian', 'senha': 'gremio'},
{'nome': 'Leandro Filho', 'login': 'leandro', 'senha': 'leandro'},
{'nome': 'Geraldo', 'login': 'geraldo', 'senha': 'palmeiras'},
{'nome': 'Luiz Uchoa', 'login': 'luiz', 'senha': 'sport'},
{'nome': 'Leandra Palma', 'login': 'leandra', 'senha': 'casalbettrader'},
{'nome': 'Thiago Rodrigues', 'login': 'thiago_rodrigues', 'senha': 'rp_thiago@yahoo.com.br'},
{'nome': 'Renato do Nascimento', 'login': 'renato_do_nascimento', 'senha': 'renatonascimentoalmeida@hotmail.com'},
{'nome': 'Fernando Henrique', 'login': 'fernando_henrique', 'senha': 'Mary@1908'},
{'nome': 'Vinicius Tardelli', 'login': 'vinicius_tardelli', 'senha': 'tardellits@gmail.com'},
{'nome': 'Saulo Senna', 'login': 'saulo_senna', 'senha': 'contato@fiodor.com.br'},
{'nome': 'Gilson Paulino', 'login': 'gilson_paulino', 'senha': 'gilsongrajauink@gmail.com'},
{'nome': 'Nettuno', 'login': 'nettuno', 'senha': 'nettuno82'},
{'nome': 'Theo Borges', 'login': 'theo_borges', 'senha': 'cariocatheo'},
{'nome': 'Tiquinho', 'login': 'tiquinho', 'senha': 'tiquinhoqa'},
# {'nome': 'Anderson Salvi', 'login': 'anderson_salvi', 'senha': 'andersonsalvi@gmail.com'},
# {'nome': 'Janeilson José', 'login': 'janeilson_jose', 'senha': 'janeilson.31@gmail.com'},
{'nome': 'Wilian Malaquias', 'login': 'wilian_malaquias', 'senha': 'malakagastao@gmail.com'},
{'nome': 'Iago Maia', 'login': 'iago_maia', 'senha': 'iago.alves.maia@hotmail.com'},
{'nome': 'Rodrigo Giannoni', 'login': 'rodrigo_giannoni', 'senha': 'giannoni@gmail.com'},
{'nome': 'Alyson David', 'login': 'alyson_david', 'senha': 'alysondavidbatera@gmail.com'},
{'nome': 'Rayson Bernardo', 'login': 'rayson_bernardo', 'senha': 'rayson.bs@hotmail.com'},
{'nome': 'Dirso Ament', 'login': 'dirso_ament', 'senha': 'adilsonantonioament@gmail.com'},
{'nome': 'Wanderson Silva', 'login': 'wanderson_silva', 'senha': 'ws709959@gmail.com'},
{'nome': 'Maicon Texeira', 'login': 'maicon_texeira', 'senha': 'maicontexeiradesouza@gmail.com'},
{'nome': 'Pedro Bastos', 'login': 'pedro_bastos', 'senha': 'pedrohenriquesoaresbastos1@gmail.com'},
{'nome': 'Yuichi Kobayashi', 'login': '@Yuichi1998', 'senha': 'Yuichi1998@hotmail.com'},
{'nome': 'Geraldo Pereira', 'login': '@geraldojhpereira', 'senha': 'geraldojhp@yahoo.com.br'},
{'nome': 'Daniel Bragança', 'login': '@DanielBraganca', 'senha': 'danbraganca@gmail.com'},
{'nome': 'Eduardo Rubik', 'login': 'eduardo_rubik', 'senha': 'eduardorubik@hotmail.com'},
{'nome': 'Aurelio Felicio', 'login': 'aurelio_felicio', 'senha': 'aureliomatosfel@gmail.com'},
{'nome': 'Ronie Araujo', 'login': 'ronie_araujo', 'senha': 'cs_de_valor'},
{'nome': 'Rafael Cavalcante', 'login': 'rafael_cavalcante', 'senha': 'klcrcb@gmail.com'},
{'nome': 'Anderson Salvi', 'login': 'anderson_salvi', 'senha': 'andersonsalvi@gmail.com'},
{'nome': 'Willyan Ribeiro', 'login': 'willyan_ribeiro', 'senha': 'willyanribeiro021@gmail.com'},
{'nome': 'Mozer Barreto', 'login': 'mozer_barreto', 'senha': 'mowcb1914@gmail.com'},
{'nome': 'João Marcelo Farina', 'login': 'jmfarina', 'senha': '@jmfarina'},
{'nome': 'Rapha Ferreira', 'login': 'rapha_ferreira', 'senha': '@raphaelph52'},
{'nome': 'Aurelio Felicio', 'login': 'aurelio_felicio', 'senha': 'aureliomatosfel@gmail.com'},
{'nome': 'Marcelo Cruz', 'login': 'marcelo_cruz', 'senha': 'marcelocruz190381@gmail.com'},
{'nome': 'Thalia Alves', 'login': 'thalia_alves', 'senha': 'thalia.alvesjs@gmail.com'},
{'nome': 'Giovane Larangeira', 'login': 'giovane_larangeira', 'senha': 'giovanelarangeira22@gmail.com'},
{'nome': 'Marcão', 'login': 'marcao', 'senha': 'oliveira.marcoantonio9@gmail.com'},
{'nome': 'Jose Alberto', 'login': 'jose_alberto', 'senha': 'zezotte@yahoo.fr'},
{'nome': 'Andre Muzzo', 'login': 'AndreMuzzo', 'senha': '@Andremuzzo'},
{'nome': 'Nicson Silva', 'login': 'NicsonSilva', 'senha': '@nicsonsilva'},
{'nome': 'Ivson Alves', 'login': 'IvsonAlves', 'senha': '@Valdomiro'},
{'nome': 'Rafael Ferreyro', 'login': 'RafaelFerreyro', 'senha': '@rafaelferreyro'},
{'nome': 'Rodrigo Bonotto', 'login': 'RodrigoBonotto', 'senha': '@Rodrigobonotoo'},
{'nome': 'Aurelio Felicio', 'login': 'AurelioFelicio', 'senha': '@aureliomatosfel'},
{'nome': 'Tiago Passos', 'login': 'TiagoPassos', 'senha': '@Tiago520'},
{'nome': 'Cleilson Bezerra', 'login': 'CleilsonBezerra', 'senha': '@Clei_Bezerra'},
{'nome': 'Yuri Moura', 'login': 'YuriMoura', 'senha': '@yuri_jose'},
{'nome': 'Robson Moraes', 'login': 'RobsonMoraes', 'senha': '@RobsonMoraes1'},
{'nome': 'Paulo Roque', 'login': 'PauloRoque', 'senha': '@pauloroque2'},
{'nome': 'Michell Silva', 'login': 'MichellSilva', 'senha': '@michellsts'},
{'nome': 'Dario Medeiros', 'login': 'DarioMedeiros', 'senha': '@Dariomedguerra'},
{'nome': 'Deivid Santana', 'login': 'DeividSantana', 'senha': '@Deividsantana'},
{'nome': 'Felipe Silva', 'login': 'FelipeSilva', 'senha': '@prof.felipe1990'},
{'nome': 'Ivan Bianzeno', 'login': 'IvanBianzeno', 'senha': '@ivanbianzeno'},
{'nome': 'Marcello Murakami', 'login': 'MarcelloMurakami', 'senha': '@marcello.yuji'},
{'nome': 'Francisco Teixeira', 'login': 'FranciscoTeixeira', 'senha': '@franciscoandreteixeira5'},
# {'nome': 'Michael Eudes', 'login': 'MichaelEudes', 'senha': '@eudesjornalismo'},
{'nome': 'Hiam Costa', 'login': 'HiamCosta', 'senha': '@hiamcosta224'},
{'nome': 'Alexandre Nemetz', 'login': 'AlexandreNemetz', 'senha': '@alexandrenemetz'},
{'nome': 'Bruno Quatrochi', 'login': 'BrunoQuatrochi', 'senha': '@b.quatrochi'},
{'nome': 'Gercina Veloso', 'login': 'GercinaVeloso', 'senha': '@gsbveloso_silvania'},
# {'nome': 'Edson da Silva', 'login': 'EdsonSilva', 'senha': '@myfamilydobarulho'},
{'nome': 'Rafael Trevizani', 'login': 'RafaelTrevizani', 'senha': '@trevizanirafael'},
{'nome': 'Leonardo Dambrós', 'login': 'LeonardoDambros', 'senha': '@nardo_quadros'},
{'nome': 'Juliane Borges', 'login': 'JulianeBorges', 'senha': '@julianepborges'},
# {'nome': 'Rondinei Machado', 'login': 'RondineiMachado', 'senha': '@ronn.machado'},
# {'nome': 'Marco Gil Morais', 'login': 'MarcoGilMorais', 'senha': '@marco.gil.morais'},
{'nome': 'Carlos Santos', 'login': 'CarlosSantos', 'senha': '@carlosdossoofi'},
{'nome': 'Wesley Penido', 'login': 'WesleyPenido', 'senha': '@wesleynido'},
{'nome': 'Maicon Texeira', 'login': 'MaiconTexeira', 'senha': '@maicontexeiradesouza'},
{'nome': 'Leonardo Leite', 'login': 'LeonardoLeite', 'senha': '@leonardoleite.cid'},
{'nome': 'Rafael Lopez', 'login': 'RafaelLopez', 'senha': '@rafadaica3'},
{'nome': 'Mendonça Bezerra', 'login': 'MendonçaBezerra', 'senha': '@mendoncabezerra'},
# {'nome': 'Breno Barbedo', 'login': 'BrenoBarbedo', 'senha': '@bmsbarbedo'},
{'nome': 'Fabio Costa', 'login': 'FabioCosta', 'senha': '@fabiokosta1'},
{'nome': 'Mateus Hessel', 'login': 'MateusHessel', 'senha': '@mateushessel'},
# {'nome': 'Eduardo Hugo', 'login': 'EduardoHugo', 'senha': '@eduardohbd3'},
# {'nome': 'Tiago Moullim', 'login': 'TiagoMoullim', 'senha': '@tmoullim'},
# {'nome': 'Abel Thiago', 'login': 'AbelThiago', 'senha': '@abel.th23'},
# {'nome': 'Casio Rabello', 'login': 'CasioRabello', 'senha': '@rabelllllo'},
# {'nome': 'Wasley Both', 'login': 'WasleyBoth', 'senha': '@wasleyboth'},
{'nome': 'Edmundo Luna', 'login': 'EdmundoLuna', 'senha': '@edmundodelunaneto'},
# {'nome': 'Leandro Maciel', 'login': 'LeandroMaciel', 'senha': '@leandro.liriomusic'},
# {'nome': 'Leandro Vinicius', 'login': 'LeandroVinicius', 'senha': '@leovinileo'},
# {'nome': 'Thyago Danilo', 'login': 'ThyagoDanilo', 'senha': '@vasconthiago'},
# {'nome': 'Marcos Castro', 'login': 'MarcosCastro', 'senha': '@lucassousa2024'},
# {'nome': 'Diego Rangel', 'login': 'DiegoRangel', 'senha': '@Diegoerangel82'},
# {'nome': 'Alan Pereira', 'login': 'AlanPereira', 'senha': '@alanpereira733467'},
{'nome': 'Renato Vieira', 'login': 'RenatoVieira', 'senha': '@renatotagarro'},
# {'nome': 'Bruno Henrique', 'login': 'BrunoHenrique', 'senha': '@validatrader'},
{'nome': 'Cleyton Ruiz', 'login': 'CleytonRuiz', 'senha': '@ruiz.fabiano'},
{'nome': 'Lucio Silva', 'login': 'LucioSilva', 'senha': '@isaeduda70'},
{'nome': 'Jaime Costa', 'login': 'JaimeCosta', 'senha': '@jaimedasilvacosta'},
# {'nome': 'Jonathan Gomes', 'login': 'JonathanGomes', 'senha': '@jonathangomes25'},
# {'nome': 'Rafael Collaço', 'login': 'RafaelCollaco', 'senha': '@rcollaco7'},
# {'nome': 'Danilo Fuentes', 'login': 'DaniloFuentes', 'senha': '@FuentesMilhas'},
# {'nome': 'Luciane Gonçalves', 'login': 'LucianeGoncalves', 'senha': '@kauadi'},
{'nome': 'Lucas Araujo', 'login': 'LucasAraujo', 'senha': '@lucaspsicologo040810'},
# {'nome': 'Ivan Ferrari', 'login': 'IvanFerrari', 'senha': '@Ivan_MarquesK'},
# {'nome': 'Ricardo Filho', 'login': 'RicardoFilho', 'senha': '@Ricardo_Filho'},
# {'nome': 'Jocelio Junior', 'login': 'JocelioJunior', 'senha': '@jocelio55junior'},
# {'nome': 'Marcos Aurélio', 'login': 'MarcosAurelio', 'senha': '@marcosfonseca.assis'},
# {'nome': 'Haron Barbosa', 'login': 'HaronBarbosa', 'senha': '@haronbg'},
# {'nome': 'Leandro Freitas','login': 'LeandroFreitas','senha': '@leandrofreitas1983'},
# {'nome': 'Paulo Froese', 'login': 'PauloFroese', 'senha': '@froesepaulo'},
{'nome': 'Igor Heraclio', 'login': 'IgorHeraclio', 'senha': '@igor_heraclio'},
{'nome': 'Wellington Muniz', 'login': 'WellingtonMuniz', 'senha': '@muniz_cfo'},
# {'nome': 'Lucas Cândido', 'login': 'LucasCandido', 'senha': '@Lucas4cad'},
# {'nome': 'Leonardo Macedo','login': 'LeonardoMacedo','senha': '@leonardomanzini'},
# {'nome': 'Raphael Bento', 'login': 'RaphaelBento', 'senha': '@r.bento'},
# {'nome': 'Eudes Abreu', 'login': 'EudesAbreu', 'senha': '@eudesgfa'},
{'nome': 'George Rocha', 'login': 'GeorgeRocha', 'senha': '@georgerocha777'},
{'nome': 'Vitor Lourenco', 'login': 'VitorLourenco', 'senha': '@vmnsantos'},
{'nome': 'Sebastião RJ', 'login': 'SebastiaoRJ', 'senha': '@gasista10'},
# {'nome': 'Jose Liberalesso','login': 'JoseLiberalesso','senha': '@josealfredoliberalesso'},
{'nome': 'Fausto Gorodoski', 'login': 'FaustoGorodoski', 'senha': '@traderusany'},
{'nome': 'Lucas Sterssio', 'login': 'LucasSterssio', 'senha': '@LucasSter'},
{'nome': 'Odirlei Klein', 'login': 'OdirleiKlein', 'senha': '@odirleiklein'},
{'nome': 'Alessandro Aparecido', 'login': 'AlessandroAparecido', 'senha': '@aleapsantos'},
{'nome': 'Sergio Vitor', 'login': 'SergioVitor', 'senha': '@sergiovitoor'},
{'nome': 'Hugo Junio', 'login': 'HugoJunio', 'senha': '@hugojuniocruvinel007'},
{'nome': 'Aulisson Bianchet', 'login': 'AulissonBianchet', 'senha': '@aulixxm'},
{'nome': 'Daniel Martins', 'login': 'DanielMartins', 'senha': '@shamandnl'},
{'nome': 'Ivan Loiola', 'login': 'IvanLoiola', 'senha': '@ilcfilho'},
{'nome': 'João Leite', 'login': 'JoaoLeite', 'senha': '@Neto_leite'},
{'nome': 'Bruno Ruocco', 'login': 'BrunoRuocco', 'senha': '@bruno.ruocco'},
{'nome': 'Alan Silva', 'login': 'AlanSilva', 'senha': '@alancarneirodasilva'},
{'nome': 'Adjael Porela', 'login': 'AdjaelPorela', 'senha': '@adjael'},
{'nome': 'Paulo Barros', 'login': 'PauloBarros', 'senha': '@PauloAndreBarros'},
{'nome': 'Cleilson Bezerra','login': 'CleilsonBezerra','senha': '@Clei_Bezerra'},
{'nome': 'Breno Santos','login': 'BrenoSantos','senha': '@brenosantos250'},
{'nome': 'Carlos Henrique','login': 'CarlosHenrique','senha': '@henriquerobmar2017'},
{'nome': 'Douglas Minuzzi','login': 'DouglasMinuzzi','senha': '@Douglas_minuzzi'},
{'nome': 'Nathan Caixeta','login': 'NathanCaixeta','senha': '@nathancaixeta7'},
{'nome': 'John Lennon','login': 'JohnLennon','senha': '@LennonAlves'},
{'nome': 'Rodrigo Lemos','login': 'RodrigoLemos','senha': '@rodrigozx10'},
{'nome': 'Valmir Rodrigues','login': 'ValmirRodrigues','senha': '@valmirramones10'},
{'nome': 'Dario Medeiros','login': 'DarioMedeiros','senha': '@dario.natal'},
{'nome': 'Cleilson','login': 'Cleilson','senha': '@clei.jr'},
{'nome': 'Bernardo Camarotti','login': 'BernardoCamarotti','senha': '@becamarotti'},
{'nome': 'Eduardo Alves','login': 'EduardoAlves','senha': '@eduardo-eduas'},
{'nome': 'Marcos Eduardo','login': 'MarcosEduardo','senha': '@mec.eduardo'},
{'nome': 'Eduardo Oliveira','login': 'EduardoOliveira','senha': '@duduoliveiradasilva10'},
{'nome': 'João Leite','login': 'JLeite','senha': '@jnetoleite93'},
{'nome': 'Diogo Serafim','login': 'DiogoSerafim','senha': '@diogoser'},

# {'nome': 'New','login': 'New','senha': '@New'},
# {'nome': 'New','login': 'New','senha': '@New'},
# {'nome': 'New','login': 'New','senha': '@New'},

]
